# Generated by Django 3.1.1 on 2020-09-15 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('create_date', models.DateField(default='9999-12-31')),
                ('modify_date', models.DateField(auto_now=True)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babies.baby')),
                ('creator_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_photos', to=settings.AUTH_USER_MODEL)),
                ('modifier_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modified_photos', to=settings.AUTH_USER_MODEL)),
                ('permitted_groups', models.ManyToManyField(related_name='allowed_photos', to='accounts.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_tags',
            field=models.ManyToManyField(related_name='tagged_photos', to='photos.Tag'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('modify_date', models.DateField(auto_now=True)),
                ('album_tags', models.ManyToManyField(related_name='tagged_albums', to='photos.Tag')),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babies.baby')),
                ('creator_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='created_albums', to=settings.AUTH_USER_MODEL)),
                ('modifier_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='modified_albums', to=settings.AUTH_USER_MODEL)),
                ('photos', models.ManyToManyField(related_name='albums', to='photos.Photo')),
            ],
        ),
    ]
