# Generated by Django 3.1.1 on 2020-09-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
