# Generated by Django 3.1.1 on 2020-09-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20200916_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='baby_id',
            new_name='baby',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='modifier_id',
            new_name='modifier',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='baby_id',
            new_name='baby',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='modifier_id',
            new_name='modifier',
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='photo_id',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='photocomment',
            old_name='user_id',
            new_name='user',
        ),
    ]
