# Generated by Django 3.1.1 on 2020-09-15 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babies', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='baby_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babies.baby'),
        ),
        migrations.AddField(
            model_name='babyaccess',
            name='baby_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babies.baby'),
        ),
        migrations.AddField(
            model_name='babyaccess',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='visited_babies',
            field=models.ManyToManyField(related_name='visited_users', through='accounts.BabyAccess', to='babies.Baby'),
        ),
    ]
