# Generated by Django 3.1.1 on 2020-09-17 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200917_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbabyrelationship',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.group'),
        ),
    ]
