# Generated by Django 3.1.1 on 2020-09-15 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0001_initial'),
        ('accounts', '0002_auto_20200915_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBabyRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_name', models.CharField(max_length=50)),
                ('baby_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babies.baby')),
                ('group_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.group')),
                ('rank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.rank')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
