# Generated by Django 3.1.1 on 2020-09-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userbabyrelationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babyaccess',
            old_name='baby_id',
            new_name='baby',
        ),
        migrations.RenameField(
            model_name='babyaccess',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='baby_id',
            new_name='baby',
        ),
        migrations.RenameField(
            model_name='userbabyrelationship',
            old_name='baby_id',
            new_name='baby',
        ),
        migrations.RenameField(
            model_name='userbabyrelationship',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='userbabyrelationship',
            old_name='rank_id',
            new_name='rank',
        ),
        migrations.RenameField(
            model_name='userbabyrelationship',
            old_name='user_id',
            new_name='user',
        ),
    ]
